=== api-evangelist/wildapricot/json-schema/wildapricot-account-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/wildapricot/refs/heads/main/json-schema/wildapricot-account-schema.json",
  "title": "Account",
  "description": "Information about Wild Apricot account",
  "type": "object",
  "properties": {
    "Id": {
      "type": "integer",
      "description": "Account unique identifier."
    },
    "Name": {
      "type": "string",
      "description": "The account name. This corresponds to the organization name as it appears on the Organization details screen."
    },
    "Url": {
      "$ref": "#/components/schemas/ResourceUrl"
    },
    "PrimaryDomainName": {
      "type": "string",
      "description": "The primary domain name for the account."
    },
    "IsFreeAccount": {
      "type": "boolean"
    },
    "Resources": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Resource"
      },
      "description": "Collection of account-related resources."
    },
    "ContactLimitInfo": {
      "$ref": "#/components/schemas/ContactLimitInfo"
    },
    "TimeZone": {
      "$ref": "#/components/schemas/TimeZone"
    },
    "Currency": {
      "$ref": "#/components/schemas/Currency"
    },
    "Localization": {
      "$ref": "#/components/schemas/Localization"
    },
    "SquareRegisterSettings": {
      "$ref": "#/components/schemas/SquareRegisterSettings"
    },
    "PaymentSettings": {
      "$ref": "#/components/schemas/PaymentSettings"
    },
    "BillingPlan": {
      "$ref": "#/components/schemas/BillingPlan"
    }
  },
  "required": [
    "Id",
    "Name",
    "PrimaryDomainName",
    "ContactLimitInfo",
    "Currency",
    "Localization",
    "SquareRegisterSettings"
  ]
}

=== api-evangelist/wildapricot/examples/wildapricot-account-example.json
{
  "Id": 1630,
  "Name": "Jane Smith",
  "Url": null,
  "PrimaryDomainName": "Jane Smith",
  "IsFreeAccount": true,
  "Resources": [
    null
  ],
  "ContactLimitInfo": null,
  "TimeZone": null,
  "Currency": null,
  "Localization": null,
  "SquareRegisterSettings": null,
  "PaymentSettings": null,
  "BillingPlan": null
}
