=== api-evangelist/wildapricot/json-schema/wildapricot-event--registration-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/wildapricot/refs/heads/main/json-schema/wildapricot-event--registration-schema.json",
  "title": "EventRegistration",
  "description": "EventRegistration schema from WildApricot Admin API",
  "type": "object",
  "properties": {
    "Id": {
      "type": "integer",
      "description": "Unique identifier of event registration"
    },
    "Url": {
      "$ref": "#/components/schemas/ResourceUrl"
    },
    "Event": {
      "$ref": "#/components/schemas/EventStub"
    },
    "Contact": {
      "$ref": "#/components/schemas/LinkedResourceWithName"
    },
    "RegistrationType": {
      "$ref": "#/components/schemas/LinkedResourceWithName"
    },
    "RegistrationTypeId": {
      "type": "integer",
      "description": "Unique identifier of event registration type"
    },
    "GuestRegistrationsSummary": {
      "$ref": "#/components/schemas/GuestRegistrationsSummary"
    },
    "DisplayName": {
      "type": "string",
      "description": "Contact display name."
    },
    "Organization": {
      "type": "string",
      "description": "Contact display name."
    },
    "IsCheckedIn": {
      "type": "boolean",
      "default": false,
      "description": "Indicates if registrant is already checked in for event."
    },
    "RegistrationFee": {
      "type": "number",
      "format": "decimal",
      "description": "The fee for this registration including all extra charges and taxes."
    },
    "PaidSum": {
      "type": "number",
      "format": "decimal",
      "description": "The sum that the registrant has already paid for the registration."
    },
    "IsPaid": {
      "type": "boolean",
      "default": false,
      "description": "Indicates if the registrant has already paid for the registration."
    },
    "RegistrationFields": {
      "type": "array",
      "description": "A collection of registration fields values",
      "items": {
        "$ref": "#/components/schemas/FieldValue"
      }
    },
    "ShowToPublic": {
      "type": "boolean",
      "default": false,
      "description": "Indicates whether this registration can be shown to other event registrants."
    },
    "RegistrationDate": {
      "type": "string",
      "format": "datetime",
      "description": "Date and time when registration was created. (Account local time)"
    },
    "Memo": {
      "type": "string",
      "description": "Some additional notes about this registration."
    },
    "IsGuestRegistration": {
      "type": "boolean",
      "default": false,
      "description": "Boolean. True if this is a guest registration, otherwise false."
    },
    "OnWaitlist": {
      "type": "boolean",
      "default": false,
      "description": "Indicates if event registration is in waitlist."
    },
    "RecreateInvoice": {
      "type": "boolean",
      "default": false,
      "description": "Optional boolean value. If specified and equals true, related invoice will be automatically updated (or created) to match selected registration type and extra cost options."
    },
    "ParentRegistration": {
      "$ref": "#/components/schemas/LinkedResource"
    },
    "Status": {
      "$ref": "#/components/schemas/EventRegistrationStatus"
    }
  },
  "required": [
    "Id",
    "Url",
    "Event",
    "Contact",
    "RegistrationType",
    "RegistrationTypeId",
    "DisplayName",
    "Organization",
    "IsCheckedIn",
    "RegistrationFee",
    "PaidSum",
    "IsPaid",
    "ShowToPublic",
    "RegistrationDate",
    "IsGuestRegistration"
  ]
}

=== api-evangelist/wildapricot/examples/wildapricot-event--registration-example.json
{
  "Id": 3231,
  "Url": null,
  "Event": null,
  "Contact": null,
  "RegistrationType": null,
  "RegistrationTypeId": 9483,
  "GuestRegistrationsSummary": null,
  "DisplayName": "Jane Smith",
  "Organization": "example-value",
  "IsCheckedIn": false,
  "RegistrationFee": 331.31,
  "PaidSum": 44.47,
  "IsPaid": false,
  "RegistrationFields": [
    null
  ],
  "ShowToPublic": false,
  "RegistrationDate": "example-value",
  "Memo": "example-value",
  "IsGuestRegistration": false,
  "OnWaitlist": false,
  "RecreateInvoice": false,
  "ParentRegistration": null,
  "Status": null
}
