=== api-evangelist/wildapricot/json-schema/wildapricot-audit--log--item-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/wildapricot/refs/heads/main/json-schema/wildapricot-audit--log--item-schema.json",
  "title": "AuditLogItem",
  "description": "AuditLogItem schema from WildApricot Admin API",
  "type": "object",
  "properties": {
    "Id": {
      "type": "integer",
      "description": "Unique identifier."
    },
    "Url": {
      "$ref": "#/components/schemas/ResourceUrl"
    },
    "Timestamp": {
      "type": "string",
      "format": "date",
      "description": "Item creation date."
    },
    "Contact": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LinkedResource"
        },
        {
          "description": "Link to related contact."
        }
      ]
    },
    "FirstName": {
      "type": "string",
      "description": "Contact first name"
    },
    "LastName": {
      "type": "string",
      "description": "Contact last name"
    },
    "Organization": {
      "type": "string",
      "description": "Contact organization"
    },
    "Email": {
      "type": "string",
      "description": "Contact primary email."
    },
    "Message": {
      "type": "string",
      "description": "Log item text."
    },
    "Severity": {
      "type": "string",
      "description": "Log item severity level.",
      "enum": [
        "Verbose",
        "Information",
        "AttentionRequired",
        "Warning",
        "Error",
        "Critical"
      ]
    },
    "OrderType": {
      "type": "string",
      "description": "The origin of the audit log entry.",
      "enum": [
        "MembershipApplication",
        "MembershipRenewal",
        "MembershipLevelChange",
        "EventRegistration",
        "Donation",
        "ChangeBillingPlan",
        "ChangeBillingInfo",
        "LockInPlan",
        "AssociationRenewal"
      ]
    },
    "Properties": {
      "type": "object",
      "description": "Collection of audit log item properties that contains all technical information about transaction and other linked documents."
    },
    "Document": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LinkedResource"
        },
        {
          "description": "Link to related document."
        }
      ]
    },
    "DocumentType": {
      "type": "string",
      "description": "Related document type.",
      "enum": [
        "Invoice",
        "Payment",
        "CreditMemo",
        "Refund",
        "Adjustment",
        "DonationPayment",
        "InvoicePayment"
      ]
    },
    "DocumentAction": {
      "type": "string",
      "description": "Action performed on related document type.",
      "enum": [
        "Created",
        "Changed",
        "Deleted",
        "Voided",
        "Custom"
      ]
    }
  }
}

=== api-evangelist/wildapricot/examples/wildapricot-audit--log--item-example.json
{
  "Id": 1934,
  "Url": null,
  "Timestamp": "2026-05-03",
  "Contact": null,
  "FirstName": "Jane Smith",
  "LastName": "Jane Smith",
  "Organization": "example-value",
  "Email": "member@example.com",
  "Message": "example-value",
  "Severity": "Warning",
  "OrderType": "ChangeBillingInfo",
  "Properties": {},
  "Document": null,
  "DocumentType": "Adjustment",
  "DocumentAction": "Created"
}
